# This is a configuration file for fattre-8 with 16 flows and 1500 seconds.
seed = 1000
k = 8
port_rate = 32000 # process 4 packets (1000 bytes) per second
capacity = 100
weights = [1]
discipline = "DRR"

[[flows]]
flow_type = "PacketDistribution"
graph = [[0, 31]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1, 30]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[2, 29]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[3, 28]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[4, 27]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[5, 26]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[6, 25]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[7, 24]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[8, 23]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[9, 22]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[10, 21]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[11, 20]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[12, 19]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[13, 18]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[14, 17]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[15, 16]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}
