# This is a configuration file for fattre-64 with 64 flows and 1500 seconds.
seed = 1000
k = 64
port_rate = 800000 # process 100 packets (1000 bytes) per second
capacity = 10000
weights = [1]
discipline = "FIFO"

[[flows]]
flow_type = "PacketDistribution"
graph = [[31, 32]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[63, 64]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[95, 96]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[127, 128]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[159, 160]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[191, 192]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[223, 224]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[255, 256]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[287, 288]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[319, 320]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[351, 352]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[383, 384]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[415, 416]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[447, 448]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[479, 480]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[511, 512]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[543, 544]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[575, 576]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[607, 608]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[639, 640]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[671, 672]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[703, 704]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[735, 736]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[767, 768]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[799, 800]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[831, 832]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[863, 864]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[895, 896]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[927, 928]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[959, 960]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[991, 992]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1023, 1024]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1055, 1056]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1087, 1088]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1119, 1120]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1151, 1152]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1184, 1184]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1215, 1216]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1247, 1248]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1279, 1280]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1311, 1312]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}


[[flows]]
flow_type = "PacketDistribution"
graph = [[1333, 1344]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1375, 1376]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1407, 1408]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1439, 1440]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1471, 1472]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1503, 1504]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1535, 1536]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1567, 1568]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1599, 1600]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1631, 1632]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1663, 1664]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1695, 1696]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1727, 1728]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1759, 1760]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1791, 1792]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1823, 1824]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1855, 1856]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1887, 1888]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1919, 1920]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1951, 1952]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[1983, 1984]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[2015, 2016]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}

[[flows]]
flow_type = "PacketDistribution"
graph = [[2047, 0]]
initial_delay = 1.0
duration = 1500.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}
