seed = 1000
edges = [[0, 1]]
num_splitters = 0

[[switch]]
port_rate = 8000
capacity = 100
weights = [1]
discipline = "FIFO"

[[switch]]
port_rate = 8000
capacity = 100
weights = [1]
discipline = "FIFO"

[[flows]]
flow_type = "PacketDistribution"
graph = [[0, 1]]
initial_delay = 1.0
arr_dist = {type = "Uniform", low = 1, high = 1}
pkt_size_dist = {type = "Uniform", low = 1000, high = 1000}