# An example configuration file for using TCP in a FatTree topology.

seed = 100
mailbox_capacity = 100
progress = 2
duration = 1500.0

[topology]
category = "FatTree"

[topology.fat_tree]
    k = 32

[switch]
port_rate = 10000000000 # 10Gbps
capacity = 1000
weights = [1]
discipline = "FIFO"
drop = "RED"

[[flow_set]]
flow_type = "TCP"
flow_count = 200
[flow_set.traffic]
    initial_delay = 0.0
    duration = 0.1
    arr_dist = {type = "Uniform", low = 0.0008, high = 0.0008}
    pkt_size_dist = {type = "Uniform", low = 1024, high = 1024}
[flow_set.traffic.tcp]
    cc_algorithm = "TCPReno"
