# An example configuration file for using TCP in a FatTree topology.

seed = 1000

[topology]
category = "FatTree"

[topology.fat_tree]
    k = 4

[switch]
port_rate = 163840 # process 40 packets (512 bytes) per second
capacity = 100
weights = [1]
discipline = "FIFO"
drop = "RED"

[[flow_set]]
flow_type = "PacketDistribution"
flow_count = 500
[flow_set.traffic]
    initial_delay = 1.0
    duration = 150.0
    arr_dist = {type = "Uniform", low = 1, high = 1}
    pkt_size_dist = {type = "Uniform", low = 512, high = 512}
[flow_set.traffic.tcp]
    cc_algorithm = "TCPCubic"
    rtt_estimate = 0.5

[[flow]]
flow_type = "PacketDistribution"
graph = [[0, 1]]
[flow.traffic]
    initial_delay = 1.0
    duration = 50.0
    arr_dist = {type = "Uniform", low = 1, high = 1}
    pkt_size_dist = {type = "Uniform", low = 512, high = 512}
[flow.traffic.tcp]
    cc_algorithm = "TCPCubic"
    rtt_estimate = 0.5