[package]
name = "daytone"
version = "0.3.3"
description = "Daytone: A Performant Discrete-Event Simulator for Network Simulations"
authors = ["Baochun Li <bli@ece.toronto.edu>"]
repository = "https://github.com/iqua/day"
readme = "README.md"
keywords = ["network", "simulation", "framework", "time", "discrete", "events"]
categories = ["simulation", "science"]
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3"
env_logger = "0.11"
indicatif = "0.17"
indicatif-log-bridge = "0.2"
log = "0.4"
nexosim = { version = "0.3.0-beta.0" }
parking_lot = "0.12"
petgraph = "0.6"
rand = { version = "0.8", features = ["small_rng"] }
serde = { version = "1.0", features = ["derive"] }
statrs = "0.18"
thiserror = "2"
toml = "0.8"
