gpu_type = "A100"
frame = "Megatron"
model_name = "llama_7B"
world_size = 8
tensor_model_parallel_size = 1
pipeline_model_parallel = 1
expert_model_parallel_size = 1
global_batch = 8
micro_batch = 1
num_layers = 32
seq_length = 2048
hidden_size = 4096
vocab_size = 32000
ffn_hidden_size = 11008
num_attention_heads = 32
use_flash_attn = false
enable_sequence_parallel = false
result_dir = "workload/collective/training"
