[[collective]]
collective_type = "Broadcast"
flow_type = "TCP"
flow_count = 4
sources = [0]
sinks = [1, 2, 3, 4]

[collective.traffic]
initial_delay = 1.0

[[collective.traffic.packets]]
packet_id = 100
size = 2048
sequence_number = 0
timestamp = 1.0

[[collective.traffic.packets]]
packet_id = 101
size = 2048
sequence_number = 2048
timestamp = 1.2

[[collective.traffic.packets]]
packet_id = 102
size = 1024
sequence_number = 4096
timestamp = 1.4

[collective.traffic.tcp]
cc_algorithm = "Cubic"
