# Simple DRR example configuration (two classes).

seed = 42
edges = [[0, 1]]
hosts = [0, 1]
duration = 0.2
log_path = "logs/drr_simple"

[switch]
port_rate = 10000000000
capacity = 512
weights = [1, 2]
discipline = "DRR"
drop = "TailDrop"

[link]
mode = "None"

[[flow]]
flow_type = "PacketDistribution"
graph = [[0, 1]]

[flow.traffic]
initial_delay = 0.0
size = 200000
arr_dist = { type = "Uniform", low = 0.001, high = 0.001 }
pkt_size_dist = { type = "DiscreteUniform", low = 1000, high = 1000 }

[[flow]]
flow_type = "PacketDistribution"
graph = [[0, 1]]

[flow.traffic]
initial_delay = 0.0
size = 200000
arr_dist = { type = "Uniform", low = 0.001, high = 0.001 }
pkt_size_dist = { type = "DiscreteUniform", low = 1000, high = 1000 }
